Repository googleapis/doc-pipeline, pull requests merged in 2021-01, with the labels that each got.

#47 feat: remove fallback to default template
  docpipeline/generate.py
Labels: cla: yes

#49 cleanup: add support for toc.html and toc.yaml
  docpipeline/generate.py
Labels: cla: yes, type: cleanup

#51 feat: adding support for docs.metadata.json
  docpipeline/generate.py
Labels: cla: yes, type: feature request

#54 feat: include xref and xref_services in docfx.json
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes

#55 build: migrate to flakybot
  ci/trampoline_v2.sh
Labels: automerge, cla: yes

#57 chore(.github): add jskeet to CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#56 feat: include xrefmap.yml in output
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes
