Repository googleapis/doc-pipeline, pull requests merged in 2021-02, with the labels that each got.

#52 feat: adding support for examples directory
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes, type: feature request

#58 fix: accommodate docs.metadata and api directory
  docpipeline/generate.py
Labels: cla: yes, type: bug

#59 chore: remove unnecessary '-' from destination-prefix
  README.md
Labels: cla: yes

#60 fix: Use obj/examples instead of obj/snippets for samples
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes, samples

#61 refactor: create function to set everything up before calling docfx
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes

#62 feat: Add prettyprint class to snippet code blocks
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes

#63 feat: upload and download xref files
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes

#65 fix: don't output to api dir, insert xref baseUrl
  .flake8
  docpipeline/generate.py
  tests/test_generate.py
Labels: cla: yes

#69 fix: create xrefmap directories when downloading
  docpipeline/generate.py
  tests/test_generate.py
Labels: automerge, cla: yes

#72 feat: download xrefs as needed and support devsite:// xrefs
  docpipeline/generate.py
  setup.py
  tests/test_generate.py
Labels: cla: yes
